#!/bin/bash

printf "Running pre-commit hook\n"

HOOK_PATH=$(realpath $0)
# Remove "/.git/hooks/pre-commit" from abs path, source: https://stackoverflow.com/a/31728689
PROJECT_ROOT=$(echo $HOOK_PATH | rev | cut -d'/' -f4- | rev)
# Run test and lint in parallel, source: https://stackoverflow.com/a/41762802
go test $PROJECT_ROOT/... & TEST_JOB=$!
golangci-lint run $PROJECT_ROOT/... & LINT_JOB=$!
wait $TEST_JOB $LINT_JOB
